# Generated by Django 3.1.6 on 2021-02-02 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(max_length=100)),
                ('Number_of_switchboard', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='switchboard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('switchboard_number', models.PositiveSmallIntegerField()),
                ('IP_of_switchboard', models.CharField(max_length=15)),
            ],
        ),
    ]
